import { VerticalOutfitFeed } from "@/components/VerticalOutfitFeed";

// Import outfit images
import outfit1 from "@/assets/outfit-1.png";
import outfit2 from "@/assets/outfit-2.png";
import outfit3 from "@/assets/outfit-3.png";
import outfit4 from "@/assets/outfit-4.png";
import outfit5 from "@/assets/outfit-5.png";

// Import item images
import itemTurtleneck from "@/assets/item-turtleneck.png";
import itemPants from "@/assets/item-pants.png";
import itemJacket from "@/assets/item-jacket.png";
import itemShoes from "@/assets/item-shoes.png";
import itemBag from "@/assets/item-bag.png";

const Index = () => {
  const outfits = [
    {
      id: "outfit-1",
      occasion: "Outfit 1",
      image: outfit1,
      items: [
        {
          id: "1",
          name: "Водолазка без рукавов",
          brand: "Wildberries",
          category: "Топ",
          itemNumber: "425380572",
          price: 9410,
          shopUrl: "https://www.wildberries.ru/catalog/425380572/detail.aspx",
          position: { top: "25%", left: "62%" },
          placement: "above" as const,
          image: itemTurtleneck,
        },
        {
          id: "2",
          name: "Брюки классические",
          brand: "Wildberries",
          category: "Брюки",
          itemNumber: "476090600",
          price: 9410,
          shopUrl: "https://www.wildberries.ru/catalog/476090600/detail.aspx",
          position: { top: "58%", left: "68%" },
          placement: "below" as const,
          image: itemPants,
        },
        {
          id: "3",
          name: "Жакет классический",
          brand: "Wildberries",
          category: "Жакет",
          itemNumber: "500291576",
          price: 9410,
          shopUrl: "https://www.wildberries.ru/catalog/500291576/detail.aspx",
          position: { top: "22%", left: "35%" },
          placement: "above" as const,
          image: itemJacket,
        },
        {
          id: "4",
          name: "Туфли лодочки",
          brand: "Wildberries",
          category: "Обувь",
          itemNumber: "301698003",
          price: 9410,
          shopUrl: "https://www.wildberries.ru/catalog/301698003/detail.aspx",
          position: { top: "68%", left: "58%" },
          placement: "below" as const,
          image: itemShoes,
        },
        {
          id: "5",
          name: "Сумка черная",
          brand: "Wildberries",
          category: "Сумка",
          itemNumber: "360419398",
          price: 9410,
          shopUrl: "https://www.wildberries.ru/catalog/360419398/detail.aspx",
          position: { top: "68%", left: "18%" },
          placement: "below" as const,
          image: itemBag,
        },
      ],
    },
    {
      id: "outfit-2",
      occasion: "Outfit 2",
      image: outfit2,
      items: [
        {
          id: "6",
          name: "Куртка",
          brand: "Wildberries",
          category: "Куртка",
          itemNumber: "491770420",
          price: 2382,
          shopUrl: "https://www.wildberries.ru/catalog/491770420/detail.aspx",
          position: { top: "24%", left: "28%" },
          placement: "above" as const,
        },
        {
          id: "7",
          name: "Топ",
          brand: "Wildberries",
          category: "Топ",
          itemNumber: "491770604",
          price: 2171,
          shopUrl: "https://www.wildberries.ru/catalog/491770604/detail.aspx",
          position: { top: "30%", left: "62%" },
          placement: "above" as const,
        },
        {
          id: "8",
          name: "Юбка",
          brand: "Wildberries",
          category: "Юбка",
          itemNumber: "528817330",
          price: 2484,
          shopUrl: "https://www.wildberries.ru/catalog/528817330/detail.aspx",
          position: { top: "58%", left: "68%" },
          placement: "below" as const,
        },
        {
          id: "9",
          name: "Туфли",
          brand: "Wildberries",
          category: "Туфли",
          itemNumber: "317983171",
          price: 2092,
          shopUrl: "https://www.wildberries.ru/catalog/317983171/detail.aspx",
          position: { top: "68%", left: "66%" },
          placement: "below" as const,
        },
        {
          id: "10",
          name: "Сумка",
          brand: "Wildberries",
          category: "Сумка",
          itemNumber: "219134255",
          price: 636,
          shopUrl: "https://www.wildberries.ru/catalog/219134255/detail.aspx",
          position: { top: "72%", left: "22%" },
          placement: "below" as const,
        },
      ],
    },
    {
      id: "outfit-3",
      occasion: "Outfit 3",
      image: outfit3,
      items: [
        {
          id: "11",
          name: "Жакет",
          brand: "Wildberries",
          category: "Жакет",
          itemNumber: "400658857",
          price: 2916,
          shopUrl: "https://www.wildberries.ru/catalog/400658857/detail.aspx",
          position: { top: "26%", left: "28%" },
          placement: "above" as const,
        },
        {
          id: "12",
          name: "Платье",
          brand: "Wildberries",
          category: "Платье",
          itemNumber: "495747921",
          price: 4082,
          shopUrl: "https://www.wildberries.ru/catalog/495747921/detail.aspx",
          position: { top: "45%", left: "62%" },
          placement: "above" as const,
        },
        {
          id: "13",
          name: "Туфли",
          brand: "Wildberries",
          category: "Туфли",
          itemNumber: "414640764",
          price: 1666,
          shopUrl: "https://www.wildberries.ru/catalog/414640764/detail.aspx",
          position: { top: "68%", left: "68%" },
          placement: "below" as const,
        },
        {
          id: "14",
          name: "Сумка",
          brand: "Wildberries",
          category: "Сумка",
          itemNumber: "518965934",
          price: 8993,
          shopUrl: "https://www.wildberries.ru/catalog/518965934/detail.aspx",
          position: { top: "74%", left: "20%" },
          placement: "below" as const,
        },
      ],
    },
    {
      id: "outfit-4",
      occasion: "Outfit 4",
      image: outfit4,
      items: [
        {
          id: "15",
          name: "Футболка",
          brand: "Wildberries",
          category: "Футболка",
          itemNumber: "500293684",
          price: 2281,
          shopUrl: "https://www.wildberries.ru/catalog/500293684/detail.aspx",
          position: { top: "22%", left: "48%" },
          placement: "above" as const,
        },
        {
          id: "16",
          name: "Джинсы",
          brand: "Wildberries",
          category: "Джинсы",
          itemNumber: "311579190",
          price: 1574,
          shopUrl: "https://www.wildberries.ru/catalog/311579190/detail.aspx",
          position: { top: "52%", left: "52%" },
          placement: "below" as const,
        },
        {
          id: "17",
          name: "Кроссовки",
          brand: "Wildberries",
          category: "Кроссовки",
          itemNumber: "314358644",
          price: 1663,
          shopUrl: "https://www.wildberries.ru/catalog/314358644/detail.aspx",
          position: { top: "68%", left: "62%" },
          placement: "below" as const,
        },
        {
          id: "18",
          name: "Сумка",
          brand: "Wildberries",
          category: "Сумка",
          itemNumber: "534647773",
          price: 1788,
          shopUrl: "https://www.wildberries.ru/catalog/534647773/detail.aspx",
          position: { top: "64%", left: "20%" },
          placement: "below" as const,
        },
      ],
    },
    {
      id: "outfit-5",
      occasion: "Outfit 5",
      image: outfit5,
      items: [
        {
          id: "19",
          name: "Жакет",
          brand: "Wildberries",
          category: "Жакет",
          itemNumber: "316111333",
          price: 3548,
          shopUrl: "https://www.wildberries.ru/catalog/316111333/detail.aspx",
          position: { top: "26%", left: "30%" },
          placement: "above" as const,
        },
        {
          id: "20",
          name: "Топ",
          brand: "Wildberries",
          category: "Топ",
          itemNumber: "491770604",
          price: 2171,
          shopUrl: "https://www.wildberries.ru/catalog/491770604/detail.aspx",
          position: { top: "32%", left: "62%" },
          placement: "above" as const,
        },
        {
          id: "21",
          name: "Брюки",
          brand: "Wildberries",
          category: "Брюки",
          itemNumber: "298659975",
          price: 3574,
          shopUrl: "https://www.wildberries.ru/catalog/298659975/detail.aspx",
          position: { top: "62%", left: "66%" },
          placement: "below" as const,
        },
        {
          id: "22",
          name: "Туфли",
          brand: "Wildberries",
          category: "Туфли",
          itemNumber: "283783392",
          price: 1992,
          shopUrl: "https://www.wildberries.ru/catalog/283783392/detail.aspx",
          position: { top: "68%", left: "68%" },
          placement: "below" as const,
        },
        {
          id: "23",
          name: "Сумка",
          brand: "Wildberries",
          category: "Сумка",
          itemNumber: "448933493",
          price: 796,
          shopUrl: "https://www.wildberries.ru/catalog/448933493/detail.aspx",
          position: { top: "70%", left: "20%" },
          placement: "below" as const,
        },
      ],
    },
  ];

  return <VerticalOutfitFeed outfits={outfits} />;
};

export default Index;
